require 'vagrant-openstack-provider'

Vagrant.configure('2') do |config|

  config.vm.box       = 'openstack'
  config.ssh.username = "vagrant"
  #config.ssh.password = "firefly"
  config.ssh.private_key_path = '~/.ssh/cloud.key'
  config.ssh.insert_key = false

  config.vm.provider :openstack do |os|
    os.openstack_auth_url = 'https://api-frfly1.client.metacloud.net:5000/v2.0'
    os.openstack_image_url = 'https://api-frfly1.client.metacloud.net:9292/v1'
    os.openstack_network_url = 'https://api-frfly1.client.metacloud.net:9696/v2.0'
    os.username           = 'johnkidd'
    os.password           = '1Password!'
    os.tenant_name        = 'dev-MPOD'
    os.availability_zone  = 'frfly1'
    os.security_groups    = ['default']
    os.networks           = ['dev_mpod_net']
    os.flavor             = 'm1.small'
    os.image              = 'devops_node_base'
    os.server_name        = 'vagrant_test'
    os.keypair_name      = 'devops_node_base'
    #os.ssh_disabled      = 'true'
  end
end
